#!/bin/bash

mytar="$HOME/.local/usr/bin/tar"
#$mytar --faketime="2013-01-01 17:01:01" "$@"

if [[ ! -z $FAKETIME_TIME ]] ; then

	if [[ -x $mytar ]] ; then
		$mytar "$@" --faketime "$FAKETIME_TIME" --sort-input --owner root --group root  --numeric-owner
		exit $?
	else
		echo "ERROR: can not find an executable tar program/script in $mytar"
		exit 1
	fi

else

	if [[ -x $mytar ]] ; then
		$mytar "$@"
		exit $?
	else
		echo "ERROR: can not find an executable tar program/script in $mytar"
		exit 1
	fi

fi

echo "ERROR: end of code too early ($0)"

